# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170502_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
