# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pop_features',
            fields=[
                ('feature', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='books.Categories'),
        ),
        migrations.AddField(
            model_name='book',
            name='features',
            field=models.ManyToManyField(to='books.pop_features'),
        ),
    ]
