# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20170524_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='book',
            name='features',
            field=models.ManyToManyField(null=True, to='books.pop_features'),
        ),
    ]
