# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170524_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='books.pop_features'),
        ),
    ]
