# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20170524_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'static/img'),
        ),
    ]
