# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20170524_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'img'),
        ),
    ]
