# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20170524_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=b'img/def.jpg', null=True, upload_to=b'img'),
        ),
    ]
