# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20170524_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
