# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicable_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='part_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=30, unique=True)),
                ('part_name', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='part_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default='2017-07-13')),
                ('supplier', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part_list')),
            ],
        ),
        migrations.AddField(
            model_name='applicable_model',
            name='partId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part_list'),
        ),
    ]
