# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part_stock',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='part_stock',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='part_stock',
            name='part_id',
        ),
        migrations.RemoveField(
            model_name='part_stock',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='part_stock',
            name='supplier',
        ),
    ]
