# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part_list',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part_list',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
