# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20170713_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_processing',
            name='req_form_no',
            field=models.IntegerField(default=0),
        ),
    ]
