# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_part_processing_req_form_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_processing',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
