# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_part_processing_quantity'),
        ('vehicle_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part_processing',
            name='vehicle_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.customer_vehicle_info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part_processing',
            name='out_date',
            field=models.DateField(default='2017-07-16'),
        ),
        migrations.AlterField(
            model_name='part_stock',
            name='entry_date',
            field=models.DateField(default='2017-07-16'),
        ),
    ]
