# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_auto_20170708_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicable_model',
            old_name='part_id',
            new_name='partId',
        ),
    ]
