# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_vehicle_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VRN', models.CharField(max_length=20)),
                ('VIN', models.CharField(max_length=40)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_info')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('importDate', models.DateField(default='2017-08-12')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_first',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='model_last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_last_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('available_qty', models.IntegerField(default=0)),
                ('modelFirst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.model_first')),
            ],
        ),
        migrations.CreateModel(
            name='model_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default='2017-08-12')),
                ('amount', models.IntegerField(default=0)),
                ('mfg_year', models.IntegerField(default=0)),
                ('modelLastId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.model_last')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.CharField(max_length=1000)),
                ('availableQty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleCategory')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclemodels',
            name='vehicleName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleName'),
        ),
        migrations.AddField(
            model_name='modelstock',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleModels'),
        ),
        migrations.AddField(
            model_name='modeldetails',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleModels'),
        ),
        migrations.AddField(
            model_name='importdetails',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleModels'),
        ),
        migrations.AddField(
            model_name='customer_vehicle_info',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleModels'),
        ),
    ]
