# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_vehicle_info',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleModels'),
        ),
    ]
