# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_stock',
            name='entry_date',
            field=models.DateField(default='2017-08-06'),
        ),
    ]
