# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0002_auto_20170810_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclename',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
