# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0003_vehiclename_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdetails',
            name='importDate',
            field=models.DateField(default='2017-08-12'),
        ),
        migrations.AlterField(
            model_name='model_stock',
            name='entry_date',
            field=models.DateField(default='2017-08-12'),
        ),
        migrations.AlterField(
            model_name='modelstock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
