# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0004_auto_20170812_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
