# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0005_auto_20170812_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
