# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address_city', models.CharField(max_length=30)),
                ('address_district', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_city', models.CharField(max_length=30)),
                ('address_district', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('gender', models.BinaryField()),
                ('joined_date', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('created_date', models.DateField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
        ),
    ]
