# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
