# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:28
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170628_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
