# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170628_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='name', max_length=30),
        ),
    ]
