# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vehicle_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=30)),
                ('VRN', models.CharField(max_length=30)),
                ('dateOfSale', models.DateField(default='2017-08-10')),
                ('soldRate', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_info')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.VehicleModels')),
            ],
        ),
    ]
