# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('vehicle_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order', models.CharField(max_length=250)),
                ('job_done', models.CharField(max_length=500)),
                ('date', models.DateField(default='2017-08-10')),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_models.customer_vehicle_info')),
            ],
        ),
    ]
