# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_records',
            name='date',
            field=models.DateField(default='2017-08-12'),
        ),
    ]
